### ISSUE TITLE
TODO: 2d_random_walk.tex 

### ISSUE THREAD

**Issue by jessicalin20018** [zehuachen/group1b-phy566-sp16-duke#6]
Can Zehua help see methodology, I feel like my methodology is different from your revised code, but I have some questions for those code. Why do we need to exclude the first 3 steps?

For the discussions of the results, have anyone have a good idea what will be appropriate to put?

**Comment by zehuachen** [comment]
Thank you for writing it.

Actually when I say methodology, I mean the background theory, not the details of the algorithm implementation, since it's already in the code.

Note "for each n > 3" in problem 1(a). Probably the professor thinks the average for first 3 steps is not so good. I have not tried, but maybe it is fine to omit that. Or, actually I don't quite understand either.

**Comment by zehuachen** [comment]
One least thing can be written is, just simply answering problem 1(b): what is the diffusion coefficient.
